[package]
name = "gtk-tray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.15.4"
stray = { path = "../stray" }
tokio = { version = "1.17.0", features = ["full"] }
once_cell = "1.10.0"